### ISSUE TITLE
Create micro-demo using basic schema just to showcase DbSchema

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dbschema-demo#1]
@LuchoTurtle as discussed on our call; 📞 
**We need** to **_isolate_** the setup of **`DbSchema`** using **`GitHub Actions`** :octocat: 
**So that** we can _confirm_ that it's working in a tiny repo before using it for work-work. 🏦 

# Todo 📝 

+ [x] borrow a basic schema from an existing app e.g: search the web: 
https://www.reddit.com/r/PostgreSQL/comments/xd6bz1/sample_popular_psql_database_schema_for_learning/
_or_ use our MVP: https://github.com/dwyl/mvp/ which has a few tables ...  but maybe a Movie or Books Database is easier. You decide. 👌 
+ [x] Create a `schema.sql` file that has the `SQL` to create the schema
  > **Note**: the reason for having a `schema.sql` instead of using an `ORM` like `Ecto` or `Drizzle`
  > is general understanding by people who don't know the `ORM` but do know `SQL`. ✅ 
+ [x] ***Execute*** the `schema.sql` script to create the Postgres DB with schema
  + [ ] both on `localhost` and 
  + [ ] on `GitHub Actions`
  > Use the programming language of your pref as long as it's fairly mainstream. 🧑‍💻 
  > I would just use `Bash` if you're confident with it. But if not, use whatevs e.g. `JS/TS` or `Go`
+ [ ] Confirm that the `Postgres` DB is created either by inserting & querying data or other means of your choice. 💭 

# `.then` ... 🤞 

+ [ ] Create a `GitHub Actions` script that runs `DbSchema` _headless_ to create a `index.html` file containing the schema

# Bonus Level 👾 

+ [ ] Publish a page using `GitHub Pages` where people can view the `index.html` file online

Once this is all done - hopefully doesn't take more than a couple of hours given all the work you've already done - we can use it for work-work and hopefully deploy a single page with the schema in our docs. 🤞

**Comment by LuchoTurtle** [comment]
Okay 👌 . 

Though I'd like some clarification from their side on the licensing and how it would effect this -> https://github.com/wise-coders/dbschema/issues/132#issuecomment-2342386293.

**Comment by nelsonic** [comment]
For sure the licensing is an open question. ❓ 🙄 
But given that `work` 🏦 has the license and will _gladly_ pay more if requested, 💰 
I'm not concerned that it will get resolved. 👌 
Thanks for making progress on this. 🙏

**Comment by LuchoTurtle** [comment]
I think I need to know the license type we do have to continue making progress on this. HTML5 documentation generation is locked under the Pro edition -> https://dbschema.com/editions.html.

**Comment by nelsonic** [comment]
@LuchoTurtle please assume that money is no object and we have the most premium deluxe gold-plated diamond-encrusted VIP tier of license. 🔑
And crack on. 🙏

**Comment by LuchoTurtle** [comment]
The thing is normally, the sample script generates an HTML5 documentation from a DbSchema project file.

![image](https://github.com/user-attachments/assets/93b0c6e6-70c6-40e9-a694-6af5ac80c556)

The problem is that saving a project file is a Pro feature.

![image](https://github.com/user-attachments/assets/e96f7c09-643c-4179-921b-091228f90b35)


I'm trying to circumvent the problem by creating the project within the Groovy script. But the documentation is [really barebones](https://dbschema.com/javadoc/index.html) and I can only go for some sample scripts found in https://dbschema.com/documentation/automation-api.html to go by.

Another thing that is bugging me is that I need to find a way to force the Docker to exit the command as an error (`1`) if the groovy script fails. ~~As it stands, it doesn't. Even if it fails, the step is ran successfully (check https://github.com/dwyl/dbschema-demo/actions/runs/10840480256).~~ got it fixed.

... 🫤
